# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: slow.Po
email: olek.sa.borodie@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  personal notes
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://slowpo.kyiv.ua" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  oleksabor

oleksabor: 
  email: olek.saborodie@gmail.com
  github: oleksabor
  stackoverflow: 940182

repository: oleksabor/slowpo_pages
comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "title"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-ZS1ZKQC483"
    anonymize_ip: false # default

permalink: /:year/:title.html

# Build settings
# https://mmistakes.github.io/minimal-mistakes
theme: minimal-mistakes-jekyll
#breadcrumbs: true
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
  
social:
  name: oleksii borodai
  
paginate_path: '/page/:num/'


pagination:
  enabled: true
  per_page: 16 
  permalink: '/page/:num/'
  title: 'page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# removing tags and categories pages from the generated sitemap.xml
defaults:
  -
    scope:
      path:            "tags"
    values:
      sitemap:         false
  -
    scope:
      path:            "categories"
    values:
      sitemap:         false


plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-responsive-image 
  - jekyll-paginate-v2  
  - kramdown
whitelist:
  - jekyll-paginate-v2  

#https://github.com/wildlyinaccurate/jekyll-responsive-image
responsive_image:
  template: _includes/picture.html
  sizes:
    - width: 320
    - width: 640

       
# tagging using archive https://markusbenning.de/blog/2018/07/22/building-a-tag-cloud-for-jekyll.html 
# combined with the logarithmic distribution by https://gist.github.com/yeban/2290195 
    

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    - template.md
    - newPost.ps1
    - tmp/
    - site_template/
    - vendor/bundle
    - vendor/cache
    - .sass-cache/
    - .jekyll-cache/
    - build.sh
    - newPost.sh 
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
