# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: oleksii borodai
email: oleksa.borodie@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  personal notes
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  oleksabor

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-responsive-image 
  
#https://github.com/wildlyinaccurate/jekyll-responsive-image
responsive_image:
  template: _includes/picture.html
  sizes:
    - width: 320
    - width: 480
    - width: 800

# https://markusbenning.de/blog/2018/07/22/building-a-tag-cloud-for-jekyll.html 
jekyll-archives:
  enabled:
    - year
#    - month
    - tags
#    - categories
  layout: 'page'
  layouts:
    year: year
#    month: month
    tag: tag_and_category
  permalinks:
    year: '/:year/'
#    month: '/:year/:month/'
    tag: '/tag/:name/'
    category: '/category/:name/'
    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    - newPost.ps1
    - tmp/
    - site_template/
    - vendor/bundle
    - vendor/cache
    - .sass-cache/
    - .jekyll-cache/
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
